/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as CartImport } from './routes/cart'
import { Route as IndexImport } from './routes/index'
import { Route as CheckoutIndexImport } from './routes/checkout/index'
import { Route as AccountIndexImport } from './routes/account/index'
import { Route as CheckoutIncompleteImport } from './routes/checkout/incomplete'
import { Route as CheckoutCompleteImport } from './routes/checkout/complete'
import { Route as AccountProfileImport } from './routes/account/profile'
import { Route as AccountOrdersImport } from './routes/account/orders'
import { Route as ShopProductsIndexImport } from './routes/shop/products/index'
import { Route as AccountMyreviewsIndexImport } from './routes/account/myreviews/index'
import { Route as ShopProductsCreateImport } from './routes/shop/products_/create'
import { Route as ShopProductProductIdImport } from './routes/shop/product/$productId'
import { Route as ShopCategoryBestSellersImport } from './routes/shop/category/best-sellers'
import { Route as ShopCategoryBestDealsImport } from './routes/shop/category/best-deals'
import { Route as ShopCategoryCategoryIdImport } from './routes/shop/category/$categoryId'
import { Route as ShopReviewReviewIdIndexImport } from './routes/shop/review/$reviewId/index'
import { Route as ShopReviewReviewIdEditImport } from './routes/shop/review/$reviewId_/edit'
import { Route as ShopProductProductIdEditImport } from './routes/shop/product_/$productId/edit'
import { Route as ShopProductProductIdCreateReviewImport } from './routes/shop/product_/$productId/create-review'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutIndexRoute = CheckoutIndexImport.update({
  path: '/checkout/',
  getParentRoute: () => rootRoute,
} as any)

const AccountIndexRoute = AccountIndexImport.update({
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutIncompleteRoute = CheckoutIncompleteImport.update({
  path: '/checkout/incomplete',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutCompleteRoute = CheckoutCompleteImport.update({
  path: '/checkout/complete',
  getParentRoute: () => rootRoute,
} as any)

const AccountProfileRoute = AccountProfileImport.update({
  path: '/account/profile',
  getParentRoute: () => rootRoute,
} as any)

const AccountOrdersRoute = AccountOrdersImport.update({
  path: '/account/orders',
  getParentRoute: () => rootRoute,
} as any)

const ShopProductsIndexRoute = ShopProductsIndexImport.update({
  path: '/shop/products/',
  getParentRoute: () => rootRoute,
} as any)

const AccountMyreviewsIndexRoute = AccountMyreviewsIndexImport.update({
  path: '/account/myreviews/',
  getParentRoute: () => rootRoute,
} as any)

const ShopProductsCreateRoute = ShopProductsCreateImport.update({
  path: '/shop/products/create',
  getParentRoute: () => rootRoute,
} as any)

const ShopProductProductIdRoute = ShopProductProductIdImport.update({
  path: '/shop/product/$productId',
  getParentRoute: () => rootRoute,
} as any)

const ShopCategoryBestSellersRoute = ShopCategoryBestSellersImport.update({
  path: '/shop/category/best-sellers',
  getParentRoute: () => rootRoute,
} as any)

const ShopCategoryBestDealsRoute = ShopCategoryBestDealsImport.update({
  path: '/shop/category/best-deals',
  getParentRoute: () => rootRoute,
} as any)

const ShopCategoryCategoryIdRoute = ShopCategoryCategoryIdImport.update({
  path: '/shop/category/$categoryId',
  getParentRoute: () => rootRoute,
} as any)

const ShopReviewReviewIdIndexRoute = ShopReviewReviewIdIndexImport.update({
  path: '/shop/review/$reviewId/',
  getParentRoute: () => rootRoute,
} as any)

const ShopReviewReviewIdEditRoute = ShopReviewReviewIdEditImport.update({
  path: '/shop/review/$reviewId/edit',
  getParentRoute: () => rootRoute,
} as any)

const ShopProductProductIdEditRoute = ShopProductProductIdEditImport.update({
  path: '/shop/product/$productId/edit',
  getParentRoute: () => rootRoute,
} as any)

const ShopProductProductIdCreateReviewRoute =
  ShopProductProductIdCreateReviewImport.update({
    path: '/shop/product/$productId/create-review',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersImport
      parentRoute: typeof rootRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileImport
      parentRoute: typeof rootRoute
    }
    '/checkout/complete': {
      id: '/checkout/complete'
      path: '/checkout/complete'
      fullPath: '/checkout/complete'
      preLoaderRoute: typeof CheckoutCompleteImport
      parentRoute: typeof rootRoute
    }
    '/checkout/incomplete': {
      id: '/checkout/incomplete'
      path: '/checkout/incomplete'
      fullPath: '/checkout/incomplete'
      preLoaderRoute: typeof CheckoutIncompleteImport
      parentRoute: typeof rootRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexImport
      parentRoute: typeof rootRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexImport
      parentRoute: typeof rootRoute
    }
    '/shop/category/$categoryId': {
      id: '/shop/category/$categoryId'
      path: '/shop/category/$categoryId'
      fullPath: '/shop/category/$categoryId'
      preLoaderRoute: typeof ShopCategoryCategoryIdImport
      parentRoute: typeof rootRoute
    }
    '/shop/category/best-deals': {
      id: '/shop/category/best-deals'
      path: '/shop/category/best-deals'
      fullPath: '/shop/category/best-deals'
      preLoaderRoute: typeof ShopCategoryBestDealsImport
      parentRoute: typeof rootRoute
    }
    '/shop/category/best-sellers': {
      id: '/shop/category/best-sellers'
      path: '/shop/category/best-sellers'
      fullPath: '/shop/category/best-sellers'
      preLoaderRoute: typeof ShopCategoryBestSellersImport
      parentRoute: typeof rootRoute
    }
    '/shop/product/$productId': {
      id: '/shop/product/$productId'
      path: '/shop/product/$productId'
      fullPath: '/shop/product/$productId'
      preLoaderRoute: typeof ShopProductProductIdImport
      parentRoute: typeof rootRoute
    }
    '/shop/products/create': {
      id: '/shop/products/create'
      path: '/shop/products/create'
      fullPath: '/shop/products/create'
      preLoaderRoute: typeof ShopProductsCreateImport
      parentRoute: typeof rootRoute
    }
    '/account/myreviews/': {
      id: '/account/myreviews/'
      path: '/account/myreviews'
      fullPath: '/account/myreviews'
      preLoaderRoute: typeof AccountMyreviewsIndexImport
      parentRoute: typeof rootRoute
    }
    '/shop/products/': {
      id: '/shop/products/'
      path: '/shop/products'
      fullPath: '/shop/products'
      preLoaderRoute: typeof ShopProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/shop/product/$productId/create-review': {
      id: '/shop/product/$productId/create-review'
      path: '/shop/product/$productId/create-review'
      fullPath: '/shop/product/$productId/create-review'
      preLoaderRoute: typeof ShopProductProductIdCreateReviewImport
      parentRoute: typeof rootRoute
    }
    '/shop/product/$productId/edit': {
      id: '/shop/product/$productId/edit'
      path: '/shop/product/$productId/edit'
      fullPath: '/shop/product/$productId/edit'
      preLoaderRoute: typeof ShopProductProductIdEditImport
      parentRoute: typeof rootRoute
    }
    '/shop/review/$reviewId/edit': {
      id: '/shop/review/$reviewId/edit'
      path: '/shop/review/$reviewId/edit'
      fullPath: '/shop/review/$reviewId/edit'
      preLoaderRoute: typeof ShopReviewReviewIdEditImport
      parentRoute: typeof rootRoute
    }
    '/shop/review/$reviewId/': {
      id: '/shop/review/$reviewId/'
      path: '/shop/review/$reviewId'
      fullPath: '/shop/review/$reviewId'
      preLoaderRoute: typeof ShopReviewReviewIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/checkout/incomplete': typeof CheckoutIncompleteRoute
  '/account': typeof AccountIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/shop/category/$categoryId': typeof ShopCategoryCategoryIdRoute
  '/shop/category/best-deals': typeof ShopCategoryBestDealsRoute
  '/shop/category/best-sellers': typeof ShopCategoryBestSellersRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
  '/shop/products/create': typeof ShopProductsCreateRoute
  '/account/myreviews': typeof AccountMyreviewsIndexRoute
  '/shop/products': typeof ShopProductsIndexRoute
  '/shop/product/$productId/create-review': typeof ShopProductProductIdCreateReviewRoute
  '/shop/product/$productId/edit': typeof ShopProductProductIdEditRoute
  '/shop/review/$reviewId/edit': typeof ShopReviewReviewIdEditRoute
  '/shop/review/$reviewId': typeof ShopReviewReviewIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/checkout/incomplete': typeof CheckoutIncompleteRoute
  '/account': typeof AccountIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/shop/category/$categoryId': typeof ShopCategoryCategoryIdRoute
  '/shop/category/best-deals': typeof ShopCategoryBestDealsRoute
  '/shop/category/best-sellers': typeof ShopCategoryBestSellersRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
  '/shop/products/create': typeof ShopProductsCreateRoute
  '/account/myreviews': typeof AccountMyreviewsIndexRoute
  '/shop/products': typeof ShopProductsIndexRoute
  '/shop/product/$productId/create-review': typeof ShopProductProductIdCreateReviewRoute
  '/shop/product/$productId/edit': typeof ShopProductProductIdEditRoute
  '/shop/review/$reviewId/edit': typeof ShopReviewReviewIdEditRoute
  '/shop/review/$reviewId': typeof ShopReviewReviewIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/checkout/incomplete': typeof CheckoutIncompleteRoute
  '/account/': typeof AccountIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/shop/category/$categoryId': typeof ShopCategoryCategoryIdRoute
  '/shop/category/best-deals': typeof ShopCategoryBestDealsRoute
  '/shop/category/best-sellers': typeof ShopCategoryBestSellersRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
  '/shop/products/create': typeof ShopProductsCreateRoute
  '/account/myreviews/': typeof AccountMyreviewsIndexRoute
  '/shop/products/': typeof ShopProductsIndexRoute
  '/shop/product/$productId/create-review': typeof ShopProductProductIdCreateReviewRoute
  '/shop/product/$productId/edit': typeof ShopProductProductIdEditRoute
  '/shop/review/$reviewId/edit': typeof ShopReviewReviewIdEditRoute
  '/shop/review/$reviewId/': typeof ShopReviewReviewIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/signin'
    | '/signup'
    | '/account/orders'
    | '/account/profile'
    | '/checkout/complete'
    | '/checkout/incomplete'
    | '/account'
    | '/checkout'
    | '/shop/category/$categoryId'
    | '/shop/category/best-deals'
    | '/shop/category/best-sellers'
    | '/shop/product/$productId'
    | '/shop/products/create'
    | '/account/myreviews'
    | '/shop/products'
    | '/shop/product/$productId/create-review'
    | '/shop/product/$productId/edit'
    | '/shop/review/$reviewId/edit'
    | '/shop/review/$reviewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/signin'
    | '/signup'
    | '/account/orders'
    | '/account/profile'
    | '/checkout/complete'
    | '/checkout/incomplete'
    | '/account'
    | '/checkout'
    | '/shop/category/$categoryId'
    | '/shop/category/best-deals'
    | '/shop/category/best-sellers'
    | '/shop/product/$productId'
    | '/shop/products/create'
    | '/account/myreviews'
    | '/shop/products'
    | '/shop/product/$productId/create-review'
    | '/shop/product/$productId/edit'
    | '/shop/review/$reviewId/edit'
    | '/shop/review/$reviewId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/signin'
    | '/signup'
    | '/account/orders'
    | '/account/profile'
    | '/checkout/complete'
    | '/checkout/incomplete'
    | '/account/'
    | '/checkout/'
    | '/shop/category/$categoryId'
    | '/shop/category/best-deals'
    | '/shop/category/best-sellers'
    | '/shop/product/$productId'
    | '/shop/products/create'
    | '/account/myreviews/'
    | '/shop/products/'
    | '/shop/product/$productId/create-review'
    | '/shop/product/$productId/edit'
    | '/shop/review/$reviewId/edit'
    | '/shop/review/$reviewId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  CheckoutCompleteRoute: typeof CheckoutCompleteRoute
  CheckoutIncompleteRoute: typeof CheckoutIncompleteRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ShopCategoryCategoryIdRoute: typeof ShopCategoryCategoryIdRoute
  ShopCategoryBestDealsRoute: typeof ShopCategoryBestDealsRoute
  ShopCategoryBestSellersRoute: typeof ShopCategoryBestSellersRoute
  ShopProductProductIdRoute: typeof ShopProductProductIdRoute
  ShopProductsCreateRoute: typeof ShopProductsCreateRoute
  AccountMyreviewsIndexRoute: typeof AccountMyreviewsIndexRoute
  ShopProductsIndexRoute: typeof ShopProductsIndexRoute
  ShopProductProductIdCreateReviewRoute: typeof ShopProductProductIdCreateReviewRoute
  ShopProductProductIdEditRoute: typeof ShopProductProductIdEditRoute
  ShopReviewReviewIdEditRoute: typeof ShopReviewReviewIdEditRoute
  ShopReviewReviewIdIndexRoute: typeof ShopReviewReviewIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountProfileRoute: AccountProfileRoute,
  CheckoutCompleteRoute: CheckoutCompleteRoute,
  CheckoutIncompleteRoute: CheckoutIncompleteRoute,
  AccountIndexRoute: AccountIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ShopCategoryCategoryIdRoute: ShopCategoryCategoryIdRoute,
  ShopCategoryBestDealsRoute: ShopCategoryBestDealsRoute,
  ShopCategoryBestSellersRoute: ShopCategoryBestSellersRoute,
  ShopProductProductIdRoute: ShopProductProductIdRoute,
  ShopProductsCreateRoute: ShopProductsCreateRoute,
  AccountMyreviewsIndexRoute: AccountMyreviewsIndexRoute,
  ShopProductsIndexRoute: ShopProductsIndexRoute,
  ShopProductProductIdCreateReviewRoute: ShopProductProductIdCreateReviewRoute,
  ShopProductProductIdEditRoute: ShopProductProductIdEditRoute,
  ShopReviewReviewIdEditRoute: ShopReviewReviewIdEditRoute,
  ShopReviewReviewIdIndexRoute: ShopReviewReviewIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cart",
        "/signin",
        "/signup",
        "/account/orders",
        "/account/profile",
        "/checkout/complete",
        "/checkout/incomplete",
        "/account/",
        "/checkout/",
        "/shop/category/$categoryId",
        "/shop/category/best-deals",
        "/shop/category/best-sellers",
        "/shop/product/$productId",
        "/shop/products/create",
        "/account/myreviews/",
        "/shop/products/",
        "/shop/product/$productId/create-review",
        "/shop/product/$productId/edit",
        "/shop/review/$reviewId/edit",
        "/shop/review/$reviewId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cart": {
      "filePath": "cart.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/account/orders": {
      "filePath": "account/orders.tsx"
    },
    "/account/profile": {
      "filePath": "account/profile.tsx"
    },
    "/checkout/complete": {
      "filePath": "checkout/complete.tsx"
    },
    "/checkout/incomplete": {
      "filePath": "checkout/incomplete.tsx"
    },
    "/account/": {
      "filePath": "account/index.tsx"
    },
    "/checkout/": {
      "filePath": "checkout/index.tsx"
    },
    "/shop/category/$categoryId": {
      "filePath": "shop/category/$categoryId.tsx"
    },
    "/shop/category/best-deals": {
      "filePath": "shop/category/best-deals.tsx"
    },
    "/shop/category/best-sellers": {
      "filePath": "shop/category/best-sellers.tsx"
    },
    "/shop/product/$productId": {
      "filePath": "shop/product/$productId.tsx"
    },
    "/shop/products/create": {
      "filePath": "shop/products_/create.tsx"
    },
    "/account/myreviews/": {
      "filePath": "account/myreviews/index.tsx"
    },
    "/shop/products/": {
      "filePath": "shop/products/index.tsx"
    },
    "/shop/product/$productId/create-review": {
      "filePath": "shop/product_/$productId/create-review.tsx"
    },
    "/shop/product/$productId/edit": {
      "filePath": "shop/product_/$productId/edit.tsx"
    },
    "/shop/review/$reviewId/edit": {
      "filePath": "shop/review/$reviewId_/edit.tsx"
    },
    "/shop/review/$reviewId/": {
      "filePath": "shop/review/$reviewId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
